name: CI

on:
  push:
    branches: ['**']
  pull_request:

permissions:
  contents: read         # ler o repo
  pages: write           # publicar no Pages
  id-token: write        # OIDC para deploy-pages

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  test:
    name: Build & Test (JDK 11)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Temurin JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'
          cache: maven

      - name: Run tests (gera allure-results)
        run: mvn -B -fae -DskipTests=false clean test

      - name: Generate Allure static site
        if: always()
        run: mvn -B io.qameta.allure:allure-maven:2.12.0:report

      # Artefatos para auditoria/baixar no run
      - name: Upload surefire-reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports

      - name: Upload allure-results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: target/allure-results

      # Este é o site estático (HTML/CSS/JS) do Allure
      - name: Upload allure-site (para Pages)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-site
          path: target/site/allure-maven-plugin

  pages:
    name: Deploy Allure to GitHub Pages
    needs: test
    if: always()           # publica mesmo se testes falharem (útil para investigar)
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}

    steps:
      - name: Baixar artefato do site
        uses: actions/download-artifact@v4
        with:
          name: allure-site
          path: site

      - name: Upload para Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

      - name: Deploy
        id: deploy
        uses: actions/deploy-pages@v4
